# Generated by Django 3.0.4 on 2020-05-21 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_of_blog', models.TextField(max_length=255)),
                ('read_interval_in_minutes', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_user_id', to='userchatapp.User')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_user_id', to='userchatapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authtokens', to='userchatapp.User')),
            ],
        ),
    ]
