# Generated by Django 3.0.4 on 2020-03-07 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userchatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_user_id', to='userchatapp.User')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_user_id', to='userchatapp.User')),
            ],
        ),
    ]
