# Generated by Django 3.0.4 on 2020-03-07 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userchatapp', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authtokens', to='userchatapp.User')),
            ],
        ),
    ]
