# Generated by Django 3.0.4 on 2020-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchatapp', '0003_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_of_blog', models.CharField(max_length=2000)),
                ('read_interval_in_minutes', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
    ]
