# Generated by Django 3.0.4 on 2020-05-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchatapp', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
