# Generated by Django 3.0.4 on 2020-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchatapp', '0005_auto_20200520_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_of_blog',
            field=models.CharField(max_length=255),
        ),
    ]
