# Generated by Django 3.0.4 on 2020-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchatapp', '0008_auto_20200521_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_of_blog',
            field=models.SlugField(max_length=255),
        ),
    ]
